#######################################
# Julien Pernet 2020 for Pancaldi lab - CRCT Team 21 - INSERM
# This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#######################################

configfile: "config.yaml"
OUTPUT  = config["Output"]
DATA = config["Data"]
PHENOTYPE = config["Phenotype_file"]
ANNOTATION = config["Annotation_file"]
ARRAYTYPE = config["Array_type"]
THREADS = config["Threads"]
SIGNATURE = config["Signature"]

if config["Do_deconv"] == "yes" or config["Do_beta_values"] == "no" :
    rule all:
        input: 
            OUTPUT + "/deconvolution.txt"
elif config["Do_deconv"] == "no" :
    rule all:
        input:
            OUTPUT + "/results/beta_values.txt"

if config["Do_beta_values"] == "yes":
    rule process_meth:
        input:
            DATA
        output:
            OUTPUT + "/results/beta_values.txt"
        params:
            ANNOTATION,
            PHENOTYPE,
            THREADS,
            ARRAYTYPE
        conda:
            "Tools/methylR.yaml"
        script:
            "Tools/methylR.R"

if config["Do_deconv"] == "yes" :

    if config["Do_beta_values"]=="no":
        input_deconv = DATA
    else:
        input_deconv = rules.process_meth.output
    
    rule epidish:
        input:
            input_deconv
        output:
           OUTPUT +  "/deconvolution.txt"
        params:
            SIGNATURE
        message:
            "Running deconvolution"
        conda:
            "Tools/epidish.yaml"
        script:
            "Tools/deconvolution_epidish.R"
