#######################################
# Julien Pernet 2020 for Pancaldi lab - CRCT Team 21 - INSERM
# This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#######################################

configfile: "config.yaml"
PHENOTYPE = config["Phenotype_file"]
DATA = config["Data"]
ANNOTATION = config["Annotation_file"]
THREADS = config["Threads"]
SIGNATURE = config["Signature"]


rule all:
 input: 
    "Outputs/deconvolution.txt"

rule process_meth:
    input:
        DATA
    output:
        "Outputs/results/beta_values.txt"
    params:
        ANNOTATION,
        PHENOTYPE,
        THREADS
    conda:
        "Tools/methylR.yaml"
    script:
        "Tools/methylR.R"

rule epidish:
    input:
        "Outputs/results/beta_values.txt"
    output:
        "Outputs/deconvolution.txt"
    params:
        SIGNATURE
    message:
        "Running deconvolution"
    conda:
        "Tools/epidish.yaml"
    script:
        "Tools/deconvolution_epidish.R"