# print('INSTALL PACKAGES')
# install.packages("Rcpp",dependencies=TRUE)
# install.packages("dplyr",dependencies=TRUE)
# install.packages("argparse",dependencies=TRUE)
# install.packages(c("remotes", "devtools", "dplyr", "tidyr", "readr", "stringr", "magrittr", "purrr"))
# BiocManager::install(c("EpiDISH", "DeconRNASeq"))
# devtools::install_github("ebecht/MCPcounter",ref="master", subdir="Source")
# remotes::install_github("icbi-lab/immunedeconv")

## ------------------------------------------------------------------------------------------------------------------------------
library(readr)
library(stringr)
library(tools)
library(argparse)
library(dplyr)
library(magrittr)


## ------------------------------------------------------------------------------------------------------------------------------
parser <- ArgumentParser(description = "Run CIBERSORTx algorithm in local")
parser$add_argument("--signature_file", type = "character", required = "True", help = "Input signature (required)")
parser$add_argument("--expression_file", type = "character", required = "True", help = "Input expression (required)")
parser$add_argument("--mail", type = "character", required = "True", help = "mail validated by CIBERSORTx web (required)")
parser$add_argument("--token", type = "character", required = "True", help = "token generated by CIBERSORTx web (required)")
parser$add_argument("--output_folder", type = "character", required = "True", help = "Input reference (required)")

args <- parser$parse_args(commandArgs(trailingOnly = T))
signature_file <- args$signature_file
expression_file <- args$expression_file
token <- args$token
mail <- args$mail
output_folder <- args$output_folder

base_name <- basename(signature_file)
dirname <- dirname(signature_file)
filename_sig <- str_split(base_name, "\\.")[[1]][1]
filename_expr <- str_split(basename(expression_file), "\\.")[[1]][1]

full_sig_file_path <- file_path_as_absolute(signature_file)
full_expr_file_path <- file_path_as_absolute(expression_file)
final_output_path <- file_path_as_absolute(file.path(output_folder, str_c(filename_sig, "___CIBERSORTx_fractions___", filename_expr)))

docker_command_string <- str_c('sudo docker run --rm --user "$(id -u):$(id -g)" -v \'', file_path_as_absolute(dirname), "':/src/data -v '", final_output_path, "':/src/outdir cibersortx/fractions ", "--username ", mail, " --token ", token, " --sigmatrix '", full_sig_file_path, "' --mixture '", full_expr_file_path, "' --perm 1 --verbose FALSE --QN FALSE", sep = "")

# print(docker_command_string)
# print("")
system(docker_command_string, wait = T)
