---
title: "Figure Extra"
output:
  pdf_document: default
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.width = 15, fig.height = 17, echo = FALSE, results = "hide", warning = FALSE, message = FALSE)
```

# Imports

```{r}
library(tidyverse)
library(Hmisc)
library(ggridges)
library(ggtext)
library(reshape2)
library(glue)
library(ggpubr)
```

# Functions

```{r}
################################################################################
# Customizable corrplot functions (modified from https://www.khstats.com/blog/corr-plots/corr-plots/)
cors <- function(df, cor.stat) {
  M <- Hmisc::rcorr(as.matrix(df), type = cor.stat)
  Mdf <- map(M, ~data.frame(.x))
  return(Mdf)
}

formatted_cors <- function(df, cor.stat){
  cors(df, cor.stat) %>%
    map(~rownames_to_column(.x, var="measure1")) %>%
    map(~pivot_longer(.x, -measure1, names_to = "measure2")) %>%
    bind_rows(.id = "id") %>%
    pivot_wider(names_from = id, values_from = value) %>%
    dplyr::rename(p = P) %>%
    mutate(sig_p = ifelse(p < .05, T, F),
           p_if_sig = ifelse(sig_p, p, NA),
           r_if_sig = ifelse(sig_p, r, NA)) 
}
################################################################################

################################################################################
# Does the typical deconvolution scatterplot comparing true proportions to certain deconvolution estimates. Called inside scatterplot_wrapper
scatterplot_truevsestimate <- function(merged_data, x, y, title, color, x_lab = "", y_lab = ""){
    merged_data %>% dplyr::select(all_of(x),all_of(y)) %>%
    na.omit() -> to_plot
  
    to_plot.cor <- rcorr(data.matrix(to_plot[c(x,y)]), type = "pearson")
  
  if (to_plot.cor$P[x,y] == 0){
    p.val = "< 2.2e-16"
    } else {
      p.val = paste("=", signif(to_plot.cor$P[x,y],2))
    }
    to_plot.rmse = sqrt(colMeans((to_plot[,y] - to_plot[,x])^2, na.rm = T))
    
  
  stats <- paste("Pearson: R = ", round(to_plot.cor$r[x,y], 2),
               ", pval ", p.val, "\n",
               "RMSE = ", round(to_plot.rmse, 2), sep = "")
  
  ## plot
  your_plot <- ggplot(to_plot) +
    aes_string(x = x, y = y) +
    geom_point(color = color) +
    labs(title = title, subtitle = stats, x = x_lab, y = y_lab) +
    geom_smooth(method=lm) +
    theme_classic() +
    theme(
      plot.title=element_text(family='', face='bold', colour='black', size=25, margin=margin(t=50,b=-40)),
      plot.subtitle=element_text(family='', face='italic', colour='black', size=18, margin=margin(t=50,b=-40)),
      text = element_text(size=15)
  )
  
  return(your_plot)
}
################################################################################

################################################################################
# This function returns the Lymphocytes, Macrophages and Neutrophils summarized
# of a given method/signature.
# Works inside of ridgeplot_parse. it takes:
# -  'deconv_data': contains the deconvolution data to index and summarize. 
#
# -  'signature dictionary': contains the exact names of the method
#                           (if it works with one signature) or the signature
#                           (if it works with multiple methods). 
#
# - iterator: string to subscript the signatures_dict with either signature
#             or methods names depending where is it called
#
# - prefix: string to leave just celltype names when substracted to the columns
#             of deconv_data of the specified method (or method + signature).
#
# - celltype: name of the celltype to sumarize "Lymphocites", "Macrophages" or "Neutrophils"

ridgeplot_parse <- function(deconv_data, signatures_dictionary, key){
  
    results <- tibble(Samples = deconv_data[[key]])
    
    names_table <- deconv_data %>%
      dplyr::select(-any_of(key)) %>%
      names() %>%
      str_split_fixed("_", 2) %>%
      as_tibble(.name_repair = "unique")
    
    for (method in unique(names_table[,1,drop=T])){
      
      if (method %in% c("Epidish",
                        "DeconRNASeq",
                        "CBSX")){
        
        for (signature in names(signatures_dictionary)){ # iterates through all the signatures (the ones not present for the method will yield all 0)
          to_match <- paste(method, signature, sep = "_")
          
          for (celltype in names(signatures_dictionary[[signature]])){
            if (length(signatures_dictionary[[signature]][[celltype]]) > 0){
              name_of_summary <- paste(to_match, celltype, sep = "_")
              columns_to_summarize <- paste(to_match, signatures_dictionary[[signature]][[celltype]], sep = ".")
              
              print(paste0("Truth: ", name_of_summary))
              deconv_data %>% dplyr::select(matches(columns_to_summarize)) %>% colnames() %>% paste0("Est: ",.) %>% print()
              cat("-------------------------\n")
              deconv_data %>% dplyr::select(matches(columns_to_summarize)) %>% rowSums(.) -> results[name_of_summary]
            }
          }
    }
      } else{
        
      to_match <- method
      
      for (celltype in names(signatures_dictionary[[method]])){
        if (length(signatures_dictionary[[method]][[celltype]]) > 0){
            name_of_summary <- paste(to_match, celltype, sep = "_")
            columns_to_summarize <- paste(to_match, signatures_dictionary[[method]][[celltype]], sep = ".")
            
            deconv_data %>% dplyr::select(matches(columns_to_summarize)) %>% rowSums(.) -> results[name_of_summary]
        }
      }
    }
    }
    results %>% dplyr::select(-Samples) %>% dplyr::select(which(!colSums(., na.rm=TRUE) %in% 0)) %>% bind_cols(Samples = results$Samples,.)
}
################################################################################

################################################################################
```


```{r}
benchmark_corrplots <- function(deconv_data, true_estimates, dict, key, title){
  # build the data
  true_subset_ <- true_estimates %>%  na.exclude() %>%
    arrange(factor(get(key), levels = get(key)))
  
  common <- Reduce(intersect, list(deconv_data[[key]],
                   true_subset_[[key]]))
  
  true_subset <- dplyr::filter(true_subset_, get(key) %in% common) %>% 
    arrange(factor(get(key), levels = common))
  
  deconv_subset <- dplyr::filter(deconv_data, get(key) %in% common) %>% 
    arrange(factor(get(key), levels = common))
  
  deconv_subset_summary <- ridgeplot_parse(deconv_data = deconv_subset, signatures_dictionary = dict, key = key)
  identical(true_subset[[key]], deconv_subset_summary[[key]]) %>% stopifnot()
  
  to_corr <- inner_join(true_subset, deconv_subset_summary) %>% dplyr::select(-any_of(key))
  ct_corrplots <- list()
  store_corrs <- tibble(measure1 = character(),
                          measure2 = character(),
                          r = numeric(),
                          n = numeric(),
                          p = numeric(),
                          sig_p = logical(),
                          p_if_sig = numeric(),
                          r_if_sig = numeric())
  
    for (ct in unique(dplyr::select(true_estimates, -any_of(key)) %>% names())){
      
      substring_remove <- c(paste0("_",ct,"$"),
      "_Tirosh_sigmatrix_SuppFig_3.b",
      "_scRNA.Seq",
      "Fig2ab.",
      "_PBMCs_scRNAseq_sigmatrix",
      "sigmatrix_",
      "_Fig2cd")
      
      deconv_ct_names <- to_corr %>%
        # segregate by ct
        dplyr::select(matches(paste0(ct, "$"))) %>%
        formatted_cors(cor.stat = "pearson") %>%
        # reduce to corrs just to ground truth
        dplyr::filter(measure1 == all_of(ct), measure2 != all_of(ct)) %>%
        # rename ground truth as cancer type
        dplyr::mutate(measure2 = str_remove_all(measure2,  paste(substring_remove, collapse = "|")))
      #add to the rest of cancer type correlations
      store_corrs <- add_row(store_corrs , deconv_ct_names)
    }
    
    # Plot
    
    order <- store_corrs %>% 
      drop_na(r) %>% 
      group_by(measure2) %>%
      dplyr::summarize(r = mean(r)) %>% 
      arrange(desc(r)) %>% 
      mutate(measure1 = "Average",
             p = NA,
             sig_p = TRUE,
             p_if_sig = NA,
             r_if_sig = r ) %>%
      dplyr::relocate(measure1, .before = measure2)
    
    ## Function to highlight the "average" row
    highlight = function(x, pat, color="black", family="") {
  ifelse(grepl(pat, x), glue("<b style='font-family:{family}; color:{color}'>{x}</b>"), x)
}
    
    ct_corrplots[[ct]] <- add_row(store_corrs, order) %>% dplyr::mutate(measure2 = factor(measure2, levels = order$measure2)) %>% dplyr::arrange(factor(measure2, levels = order$measure2)) %>%
    ggplot(aes(measure1, measure2, fill=r, label=round(r_if_sig,2))) +
    geom_tile() +
      labs(x = NULL, y = NULL, fill = "Spearman's\nCorrelation", title= title, 
         subtitle="Only significant correlation coefficients shown (95% I.C.)") +
    scale_fill_gradient2(mid="#FBFEF9",low="#0C6291",high="#A63446", limits=c(-1,1)) +
    geom_text() +
    theme_classic() +
    scale_x_discrete(expand=c(0,0), labels= function(x) highlight(x, "Average", "red")) +
    scale_y_discrete(expand=c(0,0), labels= function(x) highlight(x, "Average", "red")) +
    rotate_x_text(angle = 45) + theme(axis.text.x=element_markdown()) + theme(axis.text.y=element_markdown())
   
  return(ct_corrplots)
}
```


```{r}
```

# GSE72056
## Data loading
```{r}
deconv_GSE72056 <- read_tsv("/mnt/SERVER-CRCT-STORAGE/CRCT21/Data/deconvolution_for_gemdecan/final_example_signatures/all_deconvolutions/all_deconvolutions_Melanoma_GSE72056_not_metastatic.txt") %>% dplyr::rename_with(~str_replace(.,"__", "_CBSX_"))  %>% dplyr::rename_with(~str_replace(.,"__", "_")) #! fix naming of deconv results



truth_GSE72056 <- read.table("/mnt/SERVER-CRCT-STORAGE/CRCT21/Private/Julien/gemdecan/data/facs/Facs_Melanoma_GSE72056.txt") %>% as_tibble(rownames = "Samples")

```

## Signature Dictionary construction 

```{r}
# Lists of celltypes of each signature
## signature dictionary construction (can use . as regexp!)
## uncoment print of functions to check that you detect what you want.
## non matching signatures/methods (all 0) are removed.
## validated by jacobo 05/09/2022 

dict_GSE72056 <- list()
dict_GSE72056[["BPRNACan"]] <- list(B = c("B"),
                                     CAFs = c(),
                                     CD4 = c("CD4"),
                                     CD8 = c("CD8"),
                                     Endothelial = c(),
                                     Macrophages = c("M0", "M1", "M2"),
                                     NK = c("NK"),
                                     Th = c(),
                                     Treg = c(),
                                     Cancer = c("cancer"),
                                     Other = c("Mono", "Neu"))

dict_GSE72056[["BPRNACanProMet"]] <- dict_GSE72056[["BPRNACan"]]
dict_GSE72056[["BPRNACan3DProMet"]] <- dict_GSE72056[["BPRNACan"]]


dict_GSE72056[["CBSX_Fig2ab-NSCLC_PBMCs_scRNAseq_sigmatrix"]] <- list(B = c("B.cells"),
                                     CAFs = c(),
                                     CD4 = c("T.cells.CD4"),
                                     CD8 = c("T.cells.CD8"),
                                     Endothelial = c(),
                                     Macrophages = c(),
                                     NK = c("NK.cells"),
                                     Th = c(),
                                     Treg = c(),
                                     Cancer = c(),
                                     Other = c("Monocytes","NKT.cells"))


dict_GSE72056[["CBSX_LM22"]] <- list(B = c("B.cells.naive", "B.cells.memory", "Plasma.cells"),
                                     CAFs = c(),
                                     CD4 = c("T.cells.CD4.naive", "T.cells.CD4.memory.resting", "T.cells.CD4.memory.activated"),
                                     CD8 = c("T.cells.CD8"),
                                     Endothelial = c(),
                                     Macrophages = c("Macrophages.M0", "Macrophages.M1", "Macrophages.M2"),
                                     NK = c("NK.cells.resting", "NK.cells.activated"),
                                     Th = c("T.cells.follicular.helper", "T.cells.gamma.delta"),
                                     Treg = c("T.cells.regulatory..Tregs."),
                                     Cancer = c(),
                                     Other = c("Monocytes", "Dendritic.cells.resting", "Dendritic.cells.activated", "Mast.cells.resting", "Mast.cells.activated", "Eosinophils", "Neutrophils"))

dict_GSE72056[["CBSX_scRNA-Seq_melanoma_Tirosh_sigmatrix_SuppFig_3-b"]] <- list(B = c("B.cells"),
                                     CAFs = c("CAF"),
                                     CD4 = c("T.cells.CD4"),
                                     CD8 = c("T.cells.CD8"),
                                     Endothelial = c("Endothelial.cells"),
                                     Macrophages = c("Macrophages"),
                                     NK = c("NK.cells"),
                                     Th = c(),
                                     Treg = c(),
                                     Cancer = c("Malignant"),
                                     Other = c())


dict_GSE72056[["CBSX_sigmatrix_HNSCC_Fig2cd"]] <- list(B = c("B.cells"),
                                     CAFs = c("CAFs"),
                                     CD4 = c("T.cells.CD4"),
                                     CD8 = c("T.cells.CD8"),
                                     Endothelial = c("Endothelial.cells"),
                                     Macrophages = c("Macrophages"),
                                     NK = c(),
                                     Th = c(),
                                     Treg = c(),
                                     Cancer = c("Malignant.cells"),
                                     Other = c("Dendritic.cells", "Mast.cells", "Myocytes"))


dict_GSE72056[["Quantiseq"]] <- list(B = c("B.cell"),
                                     CAFs = c(),
                                     CD4 = c("T.cell.CD4+.(non-regulatory)"),
                                     CD8 = c("T.cell.CD8+"),
                                     Endothelial = c(),
                                     Macrophages = c("Macrophage.M1", "Macrophage.M2"),
                                     NK = c("NK.cell"),
                                     Th = c(),
                                     Treg = c("T.cell.regulatory(Tregs)"),
                                     Cancer = c(),
                                     Other = c("Monocyte", "Neutrophil", "Myeloid.dendritic.cell", "uncharacterized.cell"))


dict_GSE72056[["TIL10"]] <- list(B = c("B.cells"),
                                     CAFs = c(),
                                     CD4 = c("T.cells.CD4"),
                                     CD8 = c("T.cells.CD8"),
                                     Endothelial = c(),
                                     Macrophages = c("Macrophages.M1", "Macrophages.M2"),
                                     NK = c("NK.cells"),
                                     Th = c(),
                                     Treg = c("Tregs"),
                                     Cancer = c(),
                                     Other = c("Monocytes", "Neutrophils", "Dendritic.cells"))

dict_GSE72056[["CCLE_TIL10"]] <- list(B = c("B.cells"),
                                     CAFs = c(),
                                     CD4 = c("T.cells.CD4"),
                                     CD8 = c("T.cells.CD8"),
                                     Endothelial = c(),
                                     Macrophages = c("Macrophages.M1", "Macrophages.M2"),
                                     NK = c("NK.cells"),
                                     Th = c(),
                                     Treg = c("Tregs"),
                                     Cancer = c("Cancer.cells"), #the only diff respect Til10
                                     Other = c("Monocytes", "Neutrophils", "Dendritic.cells"))

# dict_GSE72056[["CD226"]] <- list(B = c("B"),
#                                      CAFs = c(),
#                                      CD4 = c("CD4"),
#                                      CD8 = c("CD8"),
#                                      Endothelial = c(),
#                                      Macrophages = c("M1", "M2"),
#                                      NK = c("NK"),
#                                      Th = c(),
#                                      Treg = c(),
#                                      Cancer = c(),
#                                      Other = c("Mono", "Neu"))


# dict_GSE72056[[""]] <- list(B = c(),
#                                      CAFs = c(),
#                                      CD4 = c(),
#                                      CD8 = c(),
#                                      Endothelial = c(),
#                                      Macrophages = c(),
#                                      NK = c(),
#                                      Th = c(),
#                                      Treg = c(),
#                                      Cancer = c(),
#                                      Other = c())

```
## Corrplot
```{r}
corr <- benchmark_corrplots(deconv_data = deconv_GSE72056, true_estimates = truth_GSE72056, dict = dict_GSE72056, key = "Samples", title = "GSE72056")
corr
```




# Thomas RNAseq #! Change name!
## Data loading
```{r}
deconv_Thomas <- read_csv("/mnt/SERVER-CRCT-STORAGE/CRCT21/Data/deconvolution_for_gemdecan/all_deconvolutions_Thomas_RNAseq_part.txt") %>%
  dplyr::rename_with(~str_replace(.,"__", "_CBSX_")) %>%
  dplyr::rename_with(~str_replace(.,"__", "_"))#! fix naming of deconv results
 



load( "/mnt/SERVER-CRCT-STORAGE/CRCT21/Private/Julien/gemdecan/data/meyloma_ludo/meyloma.RData")
truth_Thomas <- as_tibble(FACS_Thomas_mean, rownames = "Samples") %>%  mutate(Samples = as.numeric(Samples))

```

## Signature Dictionary construction 

```{r}
# Lists of celltypes of each signature
## signature dictionary construction (can use . as regexp!)
## uncoment print of functions to check that you detect what you want.
## non matching signatures/methods (all 0) are removed.
dict_Thomas <- list()
dict_Thomas[["BPRNACan"]] <- list(CD4 = c("CD4"),
                                     CD8 = c("CD8"),
                                     NK = c("NK"))

dict_Thomas[["BPRNACanProMet"]] <- dict_Thomas[["BPRNACan"]]
dict_Thomas[["BPRNACan3DProMet"]] <- dict_Thomas[["BPRNACan"]]


dict_Thomas[["CBSX_Fig2ab-NSCLC_PBMCs_scRNAseq_sigmatrix"]] <- list(CD4 = c("T.cells.CD4"),
                                     CD8 = c("T.cells.CD8"),
                                     NK = c("NK.cells") #"NKT.cells"?
                                     )


dict_Thomas[["CBSX_LM22"]] <- list(CD4 = c("T.cells.CD4.naive", "T.cells.CD4.memory.resting", "T.cells.CD4.memory.activated"), # "T.cells.follicular.helper", "T.cells.gamma.delta", "T.cells.regulatory..Tregs."?
                                     CD8 = c("T.cells.CD8"),
                                     NK = c("NK.cells.resting", "NK.cells.activated"))

dict_Thomas[["CBSX_scRNA-Seq_melanoma_Tirosh_sigmatrix_SuppFig_3-b"]] <- list(CD4 = c("T.cells.CD4"),
                                     CD8 = c("T.cells.CD8"),
                                     NK = c("NK.cells"))


dict_Thomas[["CBSX_sigmatrix_HNSCC_Fig2cd"]] <- list(CD4 = c("T.cells.CD4"),
                                     CD8 = c("T.cells.CD8"),
                                     NK = NULL)


dict_Thomas[["Quantiseq"]] <- list(CD4 = c("T.cell.CD4+.(non-regulatory)"), # "T.cell.regulatory(Tregs)"
                                   CD8 = c("T.cell.CD8+"),
                                   NK = c("NK.cell"))

```
## Corrplot

```{r}

corr <- benchmark_corrplots(deconv_data = deconv_Thomas, true_estimates = truth_Thomas, dict = dict_Thomas, key = "Samples", title = "test")
corr
```
